### ISSUE TITLE
high cpu usage on 'com.github.benmanes.caffeine.cache.BaseMpscLinkedArrayQueue.poll'

### ISSUE THREAD

**Issue by denghongcai** [ben-manes/caffeine#401] opened 2020-03-17 15:08 UTC
```bash
"Wisp-Root-Worker-1" #5 daemon prio=5 os_prio=0 tid=0x00007fa1862c9800 nid=0x5a0 runnable [0x00007fa1524fe000]
   java.lang.Thread.State: RUNNABLE
  at com.github.benmanes.caffeine.cache.BaseMpscLinkedArrayQueue.poll(MpscGrowableArrayQueue.java:327)
  at com.github.benmanes.caffeine.cache.BoundedLocalCache.drainWriteBuffer(BoundedLocalCache.java:1255)
  at com.github.benmanes.caffeine.cache.BoundedLocalCache.maintenance(BoundedLocalCache.java:1128)
  at com.github.benmanes.caffeine.cache.BoundedLocalCache.performCleanUp(BoundedLocalCache.java:1108)
  at com.github.benmanes.caffeine.cache.BoundedLocalCache$PerformCleanupTask.run(BoundedLocalCache.java:2979)
```

using caffeine 2.6.2. thread being blocked.

any idea about it?

**Comment by ben-manes** [comment] 2020-03-17 15:12
Not offhand. I think 2.8 has the same code, which comes from jctools. If the queue has a bug we should talk with them, perhaps needing to resync to the latest version.

**Comment by denghongcai** [comment] 2020-03-17 16:05
i'll try to figure it out. but dont know where to start dig.

if i set `Caffeine.executor(Runnable::run)` to disable background thread, will be a trade off?

**Comment by ben-manes** [comment] 2020-03-17 16:15
It will run any async tasks on the caller (e.g. removal listener notifications). If you don't do anything expensive on those, then it should be fine. Its async primarily for predictable latencies, as the maintenance work is very inexpensive.

If you know that it is stuck in an infinite loop at L327 then that would indicate a race within the queue. Otherwise it might be a high write rate to discuss if the stack trace is moving between threads.

**Comment by denghongcai** [comment] 2020-03-18 01:54
i trace the process, it is stuck in infinite loop. if disable background thread, will avoid race or it may still happen when access cache.

**Comment by ben-manes** [comment] 2020-03-18 01:56
It would happen a the caller when accessing the cache.

@nitsanw are you aware of a bug in `MpscGrowableArrayQueue` since jctools 2.0?

**Comment by ben-manes** [comment] 2020-03-18 02:03
@denghongcai can you provide environment details (cpu, jvm, os, etc)? 

I don't see any major changes in jctools since we last sync'd. We are calling the `poll` method under an exclusive lock so I'm not why it would be an infinite loop when reading the code. Each time it does a volatile read, so it would have had to of obtain a stale buffer/offset pair.

**Comment by denghongcai** [comment] 2020-03-18 02:07
JVM
> java version "1.8.0_232"
  OpenJDK Runtime Environment (Alibaba 8.9.14) (build 1.8.0_232-b604)
  OpenJDK 64-Bit Server VM (Alibaba 8.9.14) (build 25.232-b604, mixed mode)

Kernel
> 4.9.151-015

CPU
> Intel(R) Xeon(R) Platinum 8163 CPU @ 2.50GHz

**Comment by ben-manes** [comment] 2020-03-18 02:12
Since that is a custom JVM, there might be some broken assumptions. From the code of mpsc and our usage, I think it follows the JMM correctly. The bugs that I've heard of in the past don't apply (Linux kernel, FJP). Is there an Alibaba jvm engineer who might be able to assist?

**Comment by denghongcai** [comment] 2020-03-18 02:17
since you heard no bug report in the past, i believe there is something wrong not in Caffeine or JCTools. i'll ask jvm guys for help.

i'll post further information here, thanks.

**Comment by ben-manes** [comment] 2020-03-20 00:15
If helpful, you can try using something like [Stresser](https://github.com/ben-manes/caffeine/blob/master/caffeine/src/test/java/com/github/benmanes/caffeine/cache/Stresser.java) in write mode to see if the maintenance thread changes over time. If it gets stuck on your JVM but not on OpenJDK. then we know it is an Alibaba issue. If not, then it is still a mystery.

**Comment by nitsanw** [comment] 2020-03-20 14:57
There were no further fixes/known bugs for this queue AFAICT. If you think the queue is the issue, and you can reproduce this issue consistently on an OpenJDK build, please file a bug with JCTools. One way to verify if JCTools is at the root of this issue is by replacing the queue with a j.u.c queue (ConcurrentLinkedQueue) and retest.
I'm struggling a bit to map the line of code in the stacktrace to JCTools code due to how it is shaded in this project, so a mapping would be helpful.

**Comment by ben-manes** [comment] 2020-04-06 06:32
Closing due lack of next steps or repudiation. Let us know if we can help.

**Closed by ben-manes** 2020-04-06 06:32 UTC
