### ISSUE TITLE
Proactive expiration

### ISSUE THREAD

**Issue by valdo404** [ben-manes/caffeine#49] opened 2016-01-27 14:58 UTC
Hi,

I think there is a bug with expirations.
When I create a cache and I don't access the elements, then expiration is never done.

But when I access the elements, it works.

```java
public class TestExpiration {
    public static void main(String[] args) throws InterruptedException {
        RemovalListener listener = new RemovalListener<String, String>() {
            @Override
            public void onRemoval(@Nullable String key, @Nullable String value, @Nonnull RemovalCause cause) {
                System.out.println(key + " " + value + " " + cause);
            }
        };

        int initialCapacity = 2;

        Cache<String, String> store = Caffeine.newBuilder()
                .expireAfterWrite(10, TimeUnit.SECONDS)
                .executor(ForkJoinPool.commonPool())
                .removalListener(listener)
                .recordStats()
                .build();


        while(true) {
            System.out.println( store.stats());
            Thread.sleep(1000);
        }
    }
}
```
```java
System.out.println(key + " " + value + " " + cause);
```
is never called

**Comment by ben-manes** [comment] 2016-01-27 17:36
This is a common misunderstanding, so advise on clarifying the documentation would be appreciated. The [rational](https://github.com/ben-manes/caffeine/wiki/Cleanup) is discussed in the user guide and the [builder](http://static.javadoc.io/com.github.ben-manes.caffeine/caffeine/2.1.0/com/github/benmanes/caffeine/cache/Caffeine.html) mentions this in the class and expiration method JavaDoc.

To expire and notify promptly would require a background thread and a high penalty for every read and/or write. The most common approach is a background thread, a O(lg k) priority queue, and weak reference tasks. This unfortunately becomes very expensive for large, high throughput caches. Because of that most caches leave expired entries in place, rely on size eviction, and do not promptly notify.

Our approach is a middle ground which has worked well in practice. The order is maintained on O(1) priority queues and expired entries are removed + notified during the cache's maintenance phase. That amortizes the penalty of locks, etc. in a similar idea of how `ArrayList` amortizes the resize penalty when elements are added. The maintenance penalty and notification is performed using the executor to avoid incurring the latency on the calling thread.

If your cache is rarely read from or modified, then you can call `cache.cleanUp()` using a scheduled executor. That is usually unnecessary though, but a good hook to be aware of.

I think that no matter what system you used, its behavior would be surprising. One that tried to promptly notify simply wouldn't scale, so it would only mask the problem during testing but failover in production. As a design trade off, I think the scheme described is the best we can manage.

**Comment by valdo404** [comment] 2016-01-28 14:34
It's true, but in my case the listener is _never_ called. Even if expiration is not proactive, we expect it to happen. Which is not the case.

**Comment by ben-manes** [comment] 2016-01-28 17:23
I'm sorry there is confusion, but I am having trouble reproducing a problem that does not fit into the design described above.

In your test you do not insert any entries into the cache. In that case then no eviction will occur.

If I insert an entry ("a", "b") into the cache prior, an eviction will be delayed until the next maintenance cycle. That is triggered by activity (reads, writes, or an explicit `cleanUp`). When I add that into the loop then the listener prints `a b EXPIRED` and statistics show `evictionCount=1`.

This is why I concluded the misunderstanding above. There is no guarantee of _when_ the listener is called when the cache is inactive.

If it helps clarify things, the test cases associated with this feature are `ExpirationTest` and `ExpireAfterWriteTest`.

**Comment by valdo404** [comment] 2016-01-28 17:25
I'm sorry. I stripped the insertion from my code. I will add them tomorrow :/

**Comment by ben-manes** [comment] 2016-02-03 17:33
Can you take another look at this?

**Comment by ben-manes** [comment] 2016-02-12 05:29
Closing because I can't find a problem. Please reopen if you are able to put together a reproducible test case that violates the described design. Thanks!

**Closed by ben-manes** 2016-02-12 05:29 UTC
