### ISSUE TITLE
CompletableFuture never gets done when set CachedThreadPool as the execurtor of async cache

### ISSUE THREAD

**Issue by Kikyou1997** [ben-manes/caffeine#893] opened 2023-03-26 15:27 UTC
As the title describes

**Comment by ben-manes** [comment] 2023-03-26 16:04
Can you provide a unit test that demonstrates your problem? There are unit tests that use a cached thread pool, so offhand we can't help without more information.

**Comment by ben-manes** [comment] 2023-03-26 23:17
From glancing at your [draft code](https://github.com/Kikyou1997/incubator-doris/commit/7bfbcde332eebd336a7fa5a68b002c033c8ae1fd), I think you might need to run `jstack` to see if a thread is stuck. For example you changed `inProgressing` from a `ConcurrentMap` to a `HashMap`, but only synchronized writes. The reads must also be synchronized or else it can result in an infinite loop (e.g. use `Collections.synchronizedMap). I don't know if that is the cause here, but you might have some small oversight like that which is getting the threads stuck.

fwiw, you might be able to leverage `orTimeout(duration)` and `copy()` to simplify your pruning of long-running requests, but that could result in different behavior than what you have now.

**Comment by ben-manes** [comment] 2023-03-27 01:43
Another aspect that you might have fixed in your code but led you astray when opening this is that your thread pools use work queues with a maximum capacity. The pool is configured to discard work (vs a caller-runs policy), so this would cause the future to never complete. It looks like you set it to `Integer.MAX_VALUE` to be unbounded, but you might have run into this with a smaller threshold and been surprised.

`Caffeine.executor` warns about this as there is no way for us to detect it,
> Beware that configuring a cache with an executor that discards tasks or never runs them may experience non-deterministic behavior.

An `Executor` that never runs the task should really be a violation of that contract as it is otherwise meaningless. A `CompletableFuture` would never finish and rely on some other actor, like `orTimeout`, to act as a safety net to recover. That means any future that your create, be it an asynchronous load or reload, is out of our control and up to you to ensure it completes eventually. For the cache's own (optional) async work, we can eventually detect a broken executor and recover by deferring to callers to catch up the maintenance work. In our case this is thanks to using bounded ring buffers, but for foreign actions it's not our responsibility. I'd recommend shedding load by having the task no-op to cancel itself rather than an executor that silently discards the work.

**Comment by Kikyou1997** [comment] 2023-03-27 02:46
Thank you very much for your reply and suggestion. This [draft](https://github.com/Kikyou1997/incubator-doris/commit/7bfbcde332eebd336a7fa5a68b002c033c8ae1fd) works fine since it doesn't use the cached thread pool. After read you reply I think I understand why cached pool didn't work, that is caused by  configuring  CachedThredPool with a maximum thread count of 10, but in my workflow, there might be much more than 10 items to be loaded at once, exceeded tasks were just discarded and that's why it would never get done.
Here is the code defining the thread pool before.
```java
    private final ThreadPoolExecutor threadPool
            = ThreadPoolManager.newDaemonCacheThreadPool(
                    10/* max thread 10*/, "STATS_FETCH", true);
```
I'll close this issue, really thanks

**Closed** 2023-03-27 02:47 UTC
