### ISSUE TITLE
Memory usage continues to grow,there seems to have never have a  eviction

### ISSUE THREAD

**Issue by itmachina** [ben-manes/caffeine#181] opened 2017-08-23 06:03 UTC
i use caffeine 2.3.5 like this:
Caffeine.newBuilder().expireAfterWrite(300L, TimeUnit.SECONDS).recordStats().maximumSize(150000L).build();

Application memory consumption has been growing，the actual amount of data in caffeine is far more than 150000.  
there seems to have never have a  eviction.

**Comment by ben-manes** [comment] 2017-08-23 06:05
Can you provide more details? A reproducible test case would be perfect.

**Comment by ben-manes** [comment] 2017-08-23 06:11
I should note that maintenance is asynchronous by default to minimize user-facing latencies. That means if you have a high write rate it will temporarily exceed the threshold, but should provide back pressure if excessive. For testing I usually use `executor(Runnable::run)` to force it to be performed on a calling thread.

[Stresser](https://github.com/ben-manes/caffeine/blob/master/caffeine/src/test/java/com/github/benmanes/caffeine/cache/Stresser.java) is an example test that tries to overwhelm the cache.

**Comment by itmachina** [comment] 2017-08-23 06:26
I tried using jmap to check the amount in the cache，At peak times，about 410000  in the cache.
I waited for an afternoon,but nothing has changed,there is no sign of declining memory usage.
I'm trying to use the timed task to call cleanup.

**Comment by ben-manes** [comment] 2017-08-23 06:29
Can you check the JDK version used in production? Earlier versions had a bug in ForkJoinPool causing it to lose tasks, including the async maintenance. You can use `Runnable::run` instead of `cleanUp` without much overhead most of the time.

**Comment by itmachina** [comment] 2017-08-23 06:31
java version "1.8.0_77"

**Comment by ben-manes** [comment] 2017-08-23 06:32
hmm, okay. That issue was fixed in 60, I believe.

**Comment by ben-manes** [comment] 2017-08-23 06:38
When I run `Stresser` using 16 writers, the eviction is rapid enough. It will exceed the threshold by a small amount, since a hard threshold would block all writes and rarely be useful.

```
---------- 00:00:30 ----------
Pending reads: 0; writes: 577
Drain status = Processing -> Required (3)
Evictions = 11,612,513
Size = 5,074 (max: 4,096)
Lock = [Locked by thread ForkJoinPool.commonPool-worker-6]
Pending tasks = 9,219,804
Max Memory = 3,817,865,216 bytes
Free Memory = 1,831,625,152 bytes
Allocated Memory = 3,778,543,616 bytes
```

```
$ java -version
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
```

Can you simplify your code to a failing test?

**Comment by itmachina** [comment] 2017-08-23 06:50
I will hava a try.

Thank you very much,

**Comment by ben-manes** [comment] 2017-08-25 01:28
Any luck narrowing this down?

**Comment by itmachina** [comment] 2017-08-25 10:15
I did some testing and found no problem with eviction.
I found that  off-heap memory taking up a lot of memory.
The `pmap` report shows that there are many memory sizes of 504k.
I try to modify `MALLOC_ARENA_MAX`, but there is no effect.
native memory overflow?maybe...I'm not sure what caused it.
:broken_heart:

**Comment by ben-manes** [comment] 2017-08-25 16:58
Well that's frustrating... The cache uses `Unsafe` as a replacement to wrapped volatile fields, e.g. `AtomicLong`, to avoid the overhead by directly operating on the heap fields. Of course if your entries have offheap semantics that must be freed, a writer or removal listener can be used. 

Sorry that I can't be of much help and please re-open if you find anything I can assist in.

**Closed by ben-manes** 2017-08-25 16:58 UTC

**Comment by drcrallen** [comment] 2017-08-26 16:16
For posterity, https://bugs.openjdk.java.net/browse/JDK-8078490 is the bug @ben-manes was referring to.
