### ISSUE TITLE
Does caffeine cache return inconsistent result?

### ISSUE THREAD

**Issue by tundeOlagunju** [ben-manes/caffeine#739] opened 2022-06-26 16:04 UTC
I am currently experiencing an issue where I save `$['names'][*] ` in caffeine cache and the value retrieved from the cache is `$['names']`.
This issue seems to be intermittent. I debugged to the point where the data being saved in the cache and I saw that the correct value is being put in the cache while an incorrect value is being retrieved for some reasons.

I am using Spring boot version 2.2.5 and I have tried several versions of caffeine cache from 2.8.3 upwards.

**Comment by ben-manes** [comment] 2022-06-26 17:11
The data is stored in `ConcurrentHashMap` and per-key operations pass are [linearizable tests](https://github.com/ben-manes/caffeine/blob/ff58dbe0be8eb6ff6ea8c5eb237e38d472f74eab/caffeine/src/test/java/com/github/benmanes/caffeine/lincheck/AbstractLincheckCacheTest.java#L32-L43). From your description there is not much to go on. I'd probably first check that your key implements equals and hashCode correctly, as otherwise that can cause mayhem.

**Comment by ben-manes** [comment] 2022-06-27 16:02
can you provide more details? A reproducible project to debug with would be ideal.

**Comment by ben-manes** [comment] 2022-06-28 00:37
Closing due to lack of details.

**Closed by ben-manes** 2022-06-28 00:37 UTC

**Comment by tundeOlagunju** [comment] 2022-06-28 05:06
Sorry for the lack of response Ben. I have tried to reproduce this but the issue here is that it is intermittent. The project is within my company and I am afraid I will be able to paste the code

**Comment by tundeOlagunju** [comment] 2022-06-28 05:09
> The data is stored in `ConcurrentHashMap` and per-key operations are [linearizable](https://github.com/ben-manes/caffeine/blob/ff58dbe0be8eb6ff6ea8c5eb237e38d472f74eab/caffeine/src/test/java/com/github/benmanes/caffeine/lincheck/AbstractLincheckCacheTest.java#L32-L43). From your description there is not much to go on. I'd probably first check that your key implements equals and hashCode correctly, as otherwise that can cause mayhem.

I am using Springboot's @Cacheable and the key is the method name which is basically a string value

**Comment by ben-manes** [comment] 2022-06-28 05:10
Thanks for following up. How is the cache configured? I know that weakKeys are incompatible with Spring Cache.

**Comment by ben-manes** [comment] 2022-06-28 05:17
> the result as a list of Object in which one of the values in the object is a JSON path.

Is the value treated as immutable by your code and the implementation? If not then you will suffer odd races and can resolve that by cloning on read if otherwise outside of your control.

**Comment by tundeOlagunju** [comment] 2022-06-28 05:19
> Thanks for following up. How is the cache configured? I know that weakKeys are incompatible with Spring Cache.

Sorry, What do you mean by weakKeys? I have something similar to the below configuration which is basically a bean with CacheManager with expireAfterWrite duration set on it.

`@Bean
public CacheManager cacheManager(Caffeine caffeine) {
    CaffeineCacheManager caffeineCacheManager = new CaffeineCacheManager();
    caffeineCacheManager.setCaffeine(caffeine);
    return caffeineCacheManager;
}`

**Comment by ben-manes** [comment] 2022-06-28 05:23
[weakKeys](https://github.com/ben-manes/caffeine/wiki/Eviction#reference-based) is an option to evict entries once the key is eligible for garbage collection. That uses reference identity for equals, and since Spring generates a key it causes the cache lookup to always miss. It doesn’t sound like you enabled that setting.

**Comment by tundeOlagunju** [comment] 2022-06-28 05:26
> > the result as a list of Object in which one of the values in the object is a JSON path. The JSON path returns inconsistent result.
> 
> Is the value treated as immutable by your code and the implementation? If not then you will suffer odd races and can resolve that by cloning on read if otherwise outside of your control.

The class being stored in the cache is not an immutable class. We put List<Change> in the cache and Change is not immutable. Also, we do Java 8 stream's filtering on the List

**Comment by tundeOlagunju** [comment] 2022-06-28 05:32
> [weakKeys](https://github.com/ben-manes/caffeine/wiki/Eviction#reference-based) is an option to evict entries once the key is eligible for garbage collection. That uses reference identity for equals, and since Spring generates a key it causes the cache lookup to always miss. It doesn’t sound like you enabled that setting.

Is cache lookup missing similar to the retrieval of a different value to the one put in the cache. It seems to affect only JSON path values in this form `$[names][*]` - asterisk at the end is dropped when retrieved

**Comment by ben-manes** [comment] 2022-06-28 05:32
Then it sounds like your usage may not be threadsafe. As multiple threads will retrieve the same instance you’ll have to ensure two readers don’t corrupt each other.

**Comment by ben-manes** [comment] 2022-06-28 05:34
A failed lookup would call your loading method again, so that the cache is useless. Nothing stored could be retrieved again because the keys are always unequal.

**Comment by tundeOlagunju** [comment] 2022-06-28 05:37
> A failed lookup would call your loading method again, so that the cache is useless. Nothing stored could be retrieved again because the keys are always unequal.

If this is the case, then I think this is not the issue because we always retrieve data from the cache but not always consistent

**Comment by ben-manes** [comment] 2022-06-28 05:38
Yeah, it sounds like you’re mutating the cached value which is unsafe.

**Comment by tundeOlagunju** [comment] 2022-06-28 05:39
> Then it sounds like your usage may not be threadsafe. As multiple threads will retrieve the same instance you’ll have to ensure two readers don’t corrupt each other.

So, you suggest I try making the method threadsafe or making the class stored in the class immutable

**Comment by ben-manes** [comment] 2022-06-28 05:42
The classes stored in the cache should be deeply immutable. If they are non final but never modified then that is fine. However often internal mutations are done by classes that appear externally as if read only, such as to cache evaluations. The json path might be corrupted because of that type of hidden side effect.

**Comment by tundeOlagunju** [comment] 2022-06-28 05:54
> The classes stored in the cache should be deeply immutable. If they are non final but never modified then that is fine. However often internal mutations are done by classes that appear externally as if read only, such as to cache evaluations. The json path might be corrupted because of that type of hidden side effect.

Thanks for your quick response. To clarify, the List itself could be mutable but the actual class itself should be completely/deeply immutable. Note: I do not modify the class itself, but I filter the List using java 8 streams and the original list is not modified

**Comment by ben-manes** [comment] 2022-06-28 06:07
A [classic example](https://www.callicoder.com/java-simpledateformat-thread-safety-issues/) is SimpleDateFormat which mutates itself when formatting a date. It was often used as a static constant and as users had no reason to suspect it would be unsafe.

**Comment by tundeOlagunju** [comment] 2022-06-28 06:21
> A [classic example](https://www.callicoder.com/java-simpledateformat-thread-safety-issues/) is SimpleDateFormat which mutates itself when formatting a date. It was often used as a static constant and users had no reason to suspect it would be unsafe.

Thanks! However, this is a class I created myself and I am not doing any mutations. So you suspect, the cache is mutating the class?

**Comment by ben-manes** [comment] 2022-06-28 06:25
I suspect that your class holds something like a JsonPath object from an external library. If like SimpleDateFormat it has internal mutations then you might see different results even though it’s usage appears read only, just like date formatting. I don’t think this library is at fault and some hidden gotcha is in your logic.

**Comment by ben-manes** [comment] 2022-06-28 06:37
Then I’m not sure. You’ll have to try seeing if it’s reproduced with a no-op or unbounded cache (e.g. Spring’s default). If you can reproduce it locally then you can begin narrowing down to the source of the problem. Sorry that I can’t be of more help.

**Comment by tundeOlagunju** [comment] 2022-06-28 06:40
> Then I’m not sure. You’ll have to try seeing if it’s reproduced with a no-op or unbounded cache (e.g. Spring’s default). If you can reproduce it locally then you can begin narrowing down to the source of the problem. Sorry that I can’t be of more help.

Thanks! I was able to reproduce it locally few times, but I have not been successful since then. I will also try to make the class immutable as well
