### ISSUE TITLE
AsyncLoadingCache seems to cache null values for a small amount of time

### ISSUE THREAD

**Issue by migesok** [ben-manes/caffeine#254] opened 2018-07-02 13:24 UTC
Not sure if it is a bug or expected behaviour of AsyncLoadingCache but it seems highly inconvenient to me:
- I have a cache which reads an async result which could possibly be `null` meaning that the value is not there yet
- on each request I have a routine which
-- tries to read the value through the cache
-- if the result is negative then the value is computed and written to the underlying storage
-- the value is then retrieved through the cache and I really expect it to be there

I have found out that if the number of concurrent requests is quite high, sometimes the second read returns `null` as well even if the underlying storage is known to have the right value. On subsequent rereads the value shows up with typical times on a busy system to be in 10-s of milliseconds.

I was able to reproduce it in quite minimal example: [gist](https://gist.github.com/migesok/3233ed7b99bdf56dbee0f9b96a37b0ca)

Typical execution result with the latest caffeine master on my MBP:
```
Failures: 803 out of 1000
```

**Comment by ben-manes** [comment] 2018-07-02 16:33
If you send a PR, then we can let TravisCI run the build.

I have noticed Gradle gets confused if you run with a JDK mismatch (output Java8 but run with JDK10). I'd recommend using `jenv` to set the shell to `1.8`, stopping the daemons or running with `--no-daemon`, and running a clean build. If it hangs, you can use `ps aux | grep java` and `jstack <pid>` to find likely culprits. From there we can try to debug the cause.

I'm not sure of a good fix, so I'd be interested in seeing your proposal.

**Comment by ben-manes** [comment] 2018-08-15 01:33
Sounds like you worked things out. I don't think there is a good fix on my end, as there are only two bad options.

1. Return a different `CompletableFuture` that what the user supplied, to wrap their computation with synchronous logic that removes from the cache before the future completes. This would invalidate any other place logic that might depend on that future instance, e.g. some work queue, where identity comparison was used. Not wrong, just a surprise. However, users can do this trick themselves.

2. Keep the current behavior, which bubbles up the `AsyncCacheLoader` future. This leaks the race condition to the caller, but such is how asynchronous code is in the real world. They'll have to consider 
the appropriate mitigation strategy.

Closing, but feel free to reopen if you want to discuss

**Closed by ben-manes** 2018-08-15 01:33 UTC

**Comment by slovdahl** [comment] 2023-03-17 12:47
A few years later we're getting hit by this too. A bit of background to start with: we have been using pure synchronous `LoadingCache`s with `CacheLoader`s doing database calls this far. We have had spurious CI test failures for a long time without being able to track them down. It turned out that our usage of Caffeine was the problem. Concurrent `CacheLoader#loadAll` and `Cache#invalidate` calls where the `loadAll` was loading the same key as the `invalidate` was called with could end up with the invalidation call essentially being ignored and the bulk load putting a stale value in the cache (https://github.com/ben-manes/caffeine/wiki/Faq#bulk-loads helped us figure this out).

So we started replacing our `Caffeine.newBuilder().build(CacheLoader)` caches with `Caffeine.newBuilder().buildAsync(CacheLoader).synchronous()`. We don't actually need or use any asynchronous APIs (or `CacheLoader`s for that matter), we only need to make sure that if `invalidate(K)` is called while cache loading is taking place, the invalidation isn't silently ignored.

If I get to dream a little bit: a `LoadingCache` with the invalidation guarantees that the `AsyncLoadingCache` is able to provide, but without the risk of a subsequent `get(K)` calls not calling the cache loader if the previous call returned `null`. Technically, it could probably be done with your suggestion 1 @ben-manes? Does this make any sense for Caffeine to support? I realize it's a lot of extra complexity and work, so it might not carry its weight. It would however feel like a safer-by-default option to use where nanosecond performance isn't a concern.

FWIW, an even simpler reproducer of this :point_down: Fails ~300-400 times out of 100 000 times on my machine with Java 17, and ~3000 with Java 8.

```java
@RepeatedTest(100_000)
void reproducer() {
    AtomicBoolean called = new AtomicBoolean(false);

    LoadingCache<Integer, String> cache = Caffeine.newBuilder()
            .buildAsync((CacheLoader<Integer, String>)key -> {
                if (called.compareAndSet(false, true)) {
                    return null;
                }

                return String.valueOf(key);
            } )
            .synchronous();

    assertThat(cache.get(1)).isNull();
    assertThat(cache.get(1)).isEqualTo("1");
}
```

**Comment by slovdahl** [comment] 2023-03-17 13:19
Hm, one interesting observation now. By using `AsyncCacheLoader` instead and (cheating by) not using the provided `Executor`, I get no test failures any more:

```java
@RepeatedTest(100_000)
void reproducer() {
    AtomicBoolean called = new AtomicBoolean(false);

    LoadingCache<Integer, String> cache = Caffeine.newBuilder()
            .buildAsync((AsyncCacheLoader<Integer, String>)(key, executor) -> {
                if (called.compareAndSet(false, true)) {
                    return CompletableFuture.completedFuture(null);
                }

                return CompletableFuture.completedFuture(String.valueOf(key));
            } )
            .synchronous();

    assertThat(cache.get(1)).isNull();
    assertThat(cache.get(1)).isEqualTo("1");
}
```

Is this just pure luck? I assumed that the `valueFuture.whenCompleted(..)` call in `LocalAsyncCache.handleCompletion` would still be done asynchronously.

**Comment by ben-manes** [comment] 2023-03-17 16:23
Unfortunately there are no good solutions to bake into the cache, but I think your idea is worth noting in the FAQ.

For an async cache the mapping is to a future value. This causes the synchronous view to lose some linearizability as the mapping is visible before the future has completed. Thus one thread can start a computation, another remove or replace it, and a third see this latest state before the original computation completes. This could violate a user's expectation if they wanted it to be done in lock-step like a synchronous cache does (per `ConcurrentHashMap`). That's easy to reason about when explicitly using an async cache as we are clear about the mappings, but if our synchronous cache was implemented this way via future values then it could cause frustration. Guava's lack of linearization has been a long-standing complaint.

That small quirk is probably okay in most cases, so your approach works nicely. An individual load is performed under the hashmap's computation and a bulk load inserts its reservation/proxy futures. If the view obtains a future it will try to join outside of the map operation, with a retry loop in some circumstances. The bulk operation will complete those futures and as the mappings are present you avoid the side loading problems. A nice win when the desired behaviors line up.

The original issue with option (1) of returning a different future could cause other surprising behavior. For example if the calls returned a different future than what was cached, the conditional operations in the `asMap()` view would be unusable. If we don't cache the original future, e.g. use a dependent action that transforms `null` to an exception, then calls like cancelation or completion are not pushed upstream. We could try to override and push them ourselves, but as this class has evolved over Java versions that is error prone.

It all gets very messy and an attempt to find the least bad option as negative behavior leaks out in all cases. In what we do today there is the ability for the user to workaround and adapt their code, and I don't think it is as easy with the alternatives.

**Comment by slovdahl** [comment] 2023-03-20 07:24
As always, thanks for the quick and insighful response!

> The original issue with option (1) of returning a different future could cause other surprising behavior. For example if the calls returned a different future than what was cached, the conditional operations in the asMap() view would be unusable. If we don't cache the original future, e.g. use a dependent action that transforms null to an exception, then calls like cancelation or completion are not pushed upstream. We could try to override and push them ourselves, but as this class has evolved over Java versions that is error prone.
>
> It all gets very messy and an attempt to find the least bad option as negative behavior leaks out in all cases. In what we do today there is the ability for the user to workaround and adapt their code, and I don't think it is as easy with the alternatives.

Yep, makes sense. So what that suggestion essentially boils down to sounds like a completely separate implementation of `LoadingCache` constructed by some new `Caffeine#build` method, which of course is hard to motivate.

> That small quirk is probably okay in most cases, so your approach works nicely. An individual load is performed under the hashmap's computation and a bulk load inserts its reservation/proxy futures. If the view obtains a future it will try to join outside of the map operation, with a retry loop in some circumstances. The bulk operation will complete those futures and as the mappings are present you avoid the side loading problems. A nice win when the desired behaviors line up.

We'll stick with this for now :+1:
