### ISSUE TITLE
CacheWriter Use-Case Examples

### ISSUE THREAD

**Issue by stevelaw** [ben-manes/caffeine#204] opened 2017-11-17 15:26 UTC
Appreciate the great work on this caching library.  As we begin to scale out over many 10's of servers, we are trying to figure out how to move from entirely in-memory caching, to a more network/distributed caching (Redis) while still relying on Caffeine for the near-cache.  

While the `CacheWriter` wiki briefly mentions a _layered cache_ use-case, it's not entirely clear to me how this scenario would be implemented using the interface.  I know it's outside the scope of the library, but it would be helpful if examples for how we might fulfill some use-cases were provided.

**Comment by ben-manes** [comment] 2017-11-17 16:00
In that type of setup, you would use Redis as a look-aside cache with a local cache. You would use a `CacheLoader` to fetch from the remote tier and then fallback to the database query. When an update is performed, typically in those setups one writes to the remote tier and then the local cache as two distinct operations. However that leaves a race, where another remote update happens and the local cache has a stale entry due to the newer value being overwritten. So it is a better practice to always invalidate or refresh the local cache and rely on loading instead.

That race could be avoided by making the local cache responsible for writing to the remote tier, too. This is effectively changing from `Map.put` to `Map.compute` so that other writes to that entry block while the remote call is in-flight. The `CacheWriter` is merely a domain oriented way of changing the internal map call, rather than doing it yourself using `Cache.asMap`.

Similarly `CacheWriter.delete` changes from `Map.remove` to `Map.computeIfPresent`. Unfortunately that mapping is wrong, because the local cache will be much smaller than the remote one. Thus, an explicit removal might be a no-op on the local cache but should still propagate externally. Instead the local cache should use `Map.compute` and pass a null value to `CacheWriter.delete`. That could be argued as an API change as it is not JavaDoc'd that way, so I've backlogged it to v3. Thankfully this probably hasn't been an issue because most often deletes aren't propagated to the cache as one instead allows the dead entry to be floating garbage that will be evicted due to inactivity.

In the case of Redis, you will probably want to use its pub-sub capabilities for cache synchronization. That way all your local caches could be invalidated or refreshed promptly due to the notification.

I hope that clarifies things. I probably won't have the time to wrap it up and put it into the `examples` folder, but would happily accept a PR if you want to give it a shot.

**Comment by stevelaw** [comment] 2017-11-17 17:25
Thanks for the quick response.  This helps point me in the right direction.

The one piece I'm unsure about is say the `CacheLoader` were to read from the remote tier as you mentioned.  Let's say when originally written to the remote tier it was given a 1 minute expiration, and as the `CacheLoader` reads the value it still has few seconds of validity remaining in the remote tier.  However, now that it's been written to the local cache, it's essentially reseting the timer to what the local cache was configured for initially. 

If true, this likely won't be much of an issue for most of the data were concerned about, but just want to make sure this is the case or not, and if there are any best practices around this scenario.

Or am I thinking about this incorrectly?

**Comment by ben-manes** [comment] 2017-11-17 17:39
That's true if you have a fixed TTL in the local cache (`expireAfterWrite`). However if you use variable expiration (`expireAfter(expiry)`) then the TTL can be synchronized assuming no clock skew. The cost is still O(1) due to a clever data structure called a TimerWheel.

Alternatively, you might listen for expiration events from Redis and invalidate the local cache. However that won't be instantaneous due to their use of random sampling.

**Comment by ben-manes** [comment] 2017-11-20 20:26
One recommendation that I forgot, which I plan to do at work someday, is to pipe the WAL into the caching tier. There are good examples of doing that with Kafka, and I hope to setup AWS Kinesis to do that from Postgres for ElasticSearch. A consumer could ingest into Redis, which ensures that the data is fed in after the transaction completes.

The benefit of using the WAL is that there are no race conditions on the server-side. If the server is shut down after the transaction completes but before the redis update, then stale data is left in the cache. Alternatively you would need a 2-phase transaction, which is undesirable. If you use the pub-sub capabilities to invalidate the local caches, then the span of holding stale data should be very short assuming the consumer is working.

Showing all of that in an example is more work, especially since its been in my backlog at work so I haven't gone through the process yet. I haven't had many problems with the more ad hoc update after the transaction, but the WAL is nicer if you have additional storage tiers to sync with.

**Comment by stevelaw** [comment] 2018-01-03 00:18
I'm finally getting back to working on implementing the scenario where we read and write through to a remote network cache.

One piece that I'm confused about is the use of both a `CacheLoader` along with a `CacheWriter` as the current wiki page for the `CacheWriter` demonstrates.

The docs mention the following:

> A mapping that is loaded (e.g. LoadingCache.get), reloaded (e.g. LoadingCache.refresh), or computed (e.g. Map.computeIfPresent) is not communicated.

If I'm using a `LoadingCache`, and relying on the loader to create the value when not present, how would I then trigger the `CacheWriter.write` to be called?

**Comment by ben-manes** [comment] 2018-01-03 00:32
You could invoke it directly within the loader, e.g. delegate to a common method.

The problem is that a writer is usually meant to update some external resource. If say the db record was updated through the cache using a writer and `cache.put`, then the cache mutation would only occur if the transaction was successful. If it failed, e.g. not null constraint, then the cache write would be lost. If the `CacheLoader` loaded the entry and those writes were communicated, then for every load it would trigger a db update.

You're case is similar, the load might be present or absent in the remote cache. You only want the `CacheWriter` to be notified if the remote cache missed and the loader then queried the db. There isn't a way to communicate that through the loader. But if an explicit write like cache.put` occurred, you probably would want that pushed to the remote cache too.

**Comment by stevelaw** [comment] 2018-01-03 00:47
Thanks for the quick response.  So the loader would call `cache.put` or invoke the writer directly somehow?

**Comment by ben-manes** [comment] 2018-01-03 02:25
Nope, the loader will insert it into the cache. It would be something like,

```java
LoadingCache<Key, Graph> cache = Caffeine.newBuilder()
  .maximumSize(10_000)
  .writer(new CacheWriter<Key, Graph>() {
    public void write(Key key, Graph graph) {
      redis.put(key, graph); // called on explicit put() or replace()
    }
    public void delete(Key key, Graph graph, RemovalCause cause) {
      if (cause == RemovalCause.EXPLICIT) {
        redis.delete(key); // or don't bother and let it be LRU'd out
      }
    }
  }).build(key -> {
    Graph graph = redis.get(key, Graph.class);
    if (graph == null) {
      graph = db.selectFrom(GRAPH).where(GRAPH.KEY.eq(key)).fetchOne();
      redis.put(key, graph);
    }
    return graph;
  });
```

**Comment by ben-manes** [comment] 2018-02-21 18:50
@stevelaw any feedback on your efforts so far? And if so, on any additions we should add to the `examples` directory?

**Comment by ben-manes** [comment] 2018-03-12 19:11
Closing, but I would gladly accept contributions to the `examples` section. Expanding to include tutorials on popular frameworks, scenarios, etc seems like a nice idea.

**Closed by ben-manes** 2018-03-12 19:11 UTC

**Comment by stevelaw** [comment] 2018-10-27 14:52
I have a very early example of what I'm thinking around this topic here - https://github.com/stevelaw/caffeine-remote-cache.

An example usage in the readme, and this is where the bulk of the work is done - https://github.com/stevelaw/caffeine-remote-cache/blob/master/MemcacheCacheLoader.java

I'd appreciate if you could tell me if I'm way in left field on this, and any suggestions would be appreciated.

Thanks

**Comment by ben-manes** [comment] 2018-10-27 18:56
I don't quite grok the expiration logic. Why not let memcached expire the entry itself, rather than fetch an expired entry client-side and reload? I'm not sure if it helps, but there is `CacheLoader#reload` method you can override.

The high-level step for the loader looks correct:
1. Fetch from memcached
2. If not present, load from source, push into memcached
3. Return loaded value

**Comment by stevelaw** [comment] 2018-10-27 21:59
Thanks.  Right, good point.  I initially had memcache performing the expiration, but tried to get cute with one idea I had, but will revert back.

Thanks for the tip about `CacheLoader#reload`.  I'll see if that can help cleanup the code.

**Comment by ebeaufay** [comment] 2022-01-16 19:09
@ben-manes, I'm in a situation where I want to synchronously write to an external resource only when values are evicted, not when they are inserted or explicitly invalidated. Is it still possible to achieve this without the CacheWriter for a write-through cache?

**Comment by ben-manes** [comment] 2022-01-16 19:34
Yes, this case is what we narrowed down to: an eviction listener. This is lambda friendly, is called within the eviction's atomic removal, and logs & swallows any exceptions. It is a `RemovalListener` that is synchronous and only called oneviction.

```java
Cache<Key, Graph> cache = Caffeine.newBuilder()
    .evictionListener((Key key, Graph graph, RemovalCause cause) -> {
        System.out.printf("%s: %s -> %s", cause, key, value);
    })
    .maximumSize(10_000)
    .build();
```

**Comment by xenoterracide** [comment] 2024-11-05 15:01
I'm confused reading this ticket hoping to find my answer. The example you show uses a method called `writer(...)` that doesn't seem to exist anymore, and I'm not certain why.

What's the intent as to how one should manage the 2nd level (that right..) persistence store when the write hooks aren't provided. I guess that the "redis" (for example) must be creating the API for you to use directly? instead of simply giving you the hook implementations. Going to dig in that now.

**Comment by ben-manes** [comment] 2024-11-05 15:46
@xenoterracide you can use [computations](https://github.com/ben-manes/caffeine/wiki/Compute) instead of writer, which was deprecated and removed in 3.0. This approach is clearer and more flexible.

Generally the cache should be an implementation detail of a class that is not directly exposed, just as one wouldn’t expect ConcurrentHashMap in an api. As most interfaces offer limited behavior, the usage of caffeine is constrained to a few methods which can control writes.

A more general interface, like Map, does require more effort which an interceptor approach makes easier. Thankfully there are decorators for collections that offer this, like ObservableMap, which means that map implementation itself doesn’t need the features natively. You might expose a decorated view of the map that ensures the atomicity, integration, etc that is needed.
